/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillChart: typeof import('./src/components/BillChart/index.vue')['default']
    UploadData: typeof import('./src/components/UploadData/index.vue')['default']
  }
}
